### ISSUE TITLE
Sherlock question

### ISSUE THREAD

**Issue by PocketChangeJ** [ENCODE-DCC/atac-seq-pipeline#138]
Hi there,
I was wondering if you would have any recommendation for running your pipeline on Sherlock for free users? 
I remember I used to be able to wrap everything up into one job that lasted around a day or so, but seems caper now submits each task as a separate job, and with my 3 replicates and long queues there is no way this will get done in 48h.. 
Thanks so much!

**Comment by leepc12** [comment]
You can run still run Caper as one job with `-b/--backend local` but it will be hard to estimate required resources for this single job since Cromwell will try to maximize parallelization (each replicate will be processed at the same time) and each task has its own resource settings (e.g. `atac.trim_adapter_cpu`).

It would be better to keep using the SLURM mode with `-b/--backend slurm` and reduce resources (`TASK_NAME_cpu`, `TASK_NAME_time_hr` and `TASK_NAME_mem_mb`) for each task to meet free user's quota in your input JSON.

**Comment by PocketChangeJ** [comment]
All right, I'll give it a try. Thank you!
