### ISSUE TITLE
Pipeline fails without blacklist file

### ISSUE THREAD

**Issue by nicolerg** [ENCODE-DCC/atac-seq-pipeline#165]
I left `BLACKLIST` empty in `build_genome_database.sh` to build a custom genome database. The database compiled, but running the pipeline failed. The pipeline runs without issue after adding a dummy blacklist file. Can you please update the docs to say a blacklist file is required or add compatibility for no blacklist file?

Attached is the Caper `troubleshoot` log when using a custom genome without a blacklist file.
[caper_troubleshoot.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3747337/caper_troubleshoot.txt)

**Comment by akundaje** [comment]
Jin - allow the pipeline to be run without a blacklist

**Comment by leepc12** [comment]
Fixed in 33df36596684789783c630473e1bbb2da89df991. I removed a param `keep_irregular_chr_in_bfilt_peak` from the pipeline. Instead, we have a new param `regex_bfilt_peak_chr_name` in a genome TSV since this is a genome specific parameter (this can also be defined in your input JSON though: `atac.regex_bfilt_peak_chr_name`). It's `chr[\dXY]+` by default. This defined chromosome names to keep in the final peaks file (with suffix `.bfilt.`). This filter is applied even without the blacklist itself. So consider `.bfilt.` peaks file as a final peaks output of the pipeline.
