### ISSUE TITLE
Normalizing Bigwigs

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ENCODE-DCC/atac-seq-pipeline#267]
Are there any plans in the future to create bigwigs that are normalized by some metric (i.e. RPKM, CPM, etc.)? 

Based on my understanding, the `p-value` and `fold-change` bigwigs are both unnormalized? 
This means comparing BigWig tracks on UCSC, for example, is not accurate to do between samples.

**Comment by akundaje** [comment]
Fold-change is very similar to CPM but with better local normalization

If C is total number of extended reads at a base
R is total number of extended reads
G is mappable genome size

CPM = C *10^6 / R

Foldchange with global normalization = C * (G / R) where G is mappable
genome size.

So the only difference is the constant in the numerator.

In reality the fold change is a bit more complicated since it uses a
conservative estimate of the normalizing constant i.e. min (G/R , g/r),
where r is number of mappable reads in a 10 Kb flanking region, g = 10 Kb

So in essence fold-change is most certainly a normalized signal. The
pvalue is the statistical significance of this normalized estimate.

-Anshul.

**Comment by YogiOnBioinformatics** [comment]
Wow @akundaje! 

Thanks so much for this extremely well explained answer to the question!
Appreciate it very much.
