### ISSUE TITLE
conda requirements_py3.txt has insufficient requirements

### ISSUE THREAD

**Issue by akmorrow13** [ENCODE-DCC/atac-seq-pipeline#58]
conda/requirements_py3.txt is missing requirements for running this pipeline. 

For example, running in python3 with the pipeline fails because `cutadapt` is not installed. This requirement is missing in requirements_py3.txt.

**Comment by leepc12** [comment]
It's not a python3 version of pipeline's environment. It is only for python3 based softwares (like IDR). You should not try to activate the python3 environment.

Use python2 environment (`encode-atac-seq-pipeline`). It internally calls `python3` in the python3 environment (`encode-atac-seq-pipeline-python3`). We had to have two separate environments for one pipeline because Conda does not allow coexistence of python2 and 3. So python3 environment is just a workaround.

**Comment by akmorrow13** [comment]
Ahh thanks for the explanation!
