### ISSUE TITLE
Stuck at WaitingForReturnCodeFile

### ISSUE THREAD

**Issue by grrompala** [ENCODE-DCC/atac-seq-pipeline#83]
I have set up this pipeline before and not encountered this issue (see attached log).

As soon as it gets to Bowtie2, nothing progresses from the Waiting point

Is this a cromwell issue? Any insight you can provide would be much appreciated.

[Output.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/2838824/Output.txt)

**Comment by yifeisun03** [comment]
@grrompala: I'm seeing the same issue here (when running using singularity). Were you able to make any progress?

As far as I can tell, this appears to just be taking a very long time. I have upwards of 20+ output *.bam files in one `call-bowtie2/shard-0/execution` directory (and about a new one every 30 minutes). These are for ~2GB fastq files. @leepc12: does this seem like expected behavior?

**Comment by leepc12** [comment]
@yifeisun03 : I thinks so.
@grrompala : `bowtie2` takes very long with large fastqs. Your log says previous steps before `bowtie2` are done successfully. Is it still hanging?

**Comment by yifeisun03** [comment]
Thanks, that seems to be the case, it did get past this step after almost 40h.

**Comment by milanmlft** [comment]
Hi,

I have the same issue while running the example. When I ran the pipeline 2 weeks ago, it completed within about an hour for the example. Tried to run the example again today, after updating everything to the latest version, but now it cannot get past the `bowtie2` step even after 2 hours.

Running the pipeline on an HPC server.

I added the outputs for my run of today and that of 2 weeks ago for comparison.

Thanks a lot for your help!

[output-2019-03-27.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3013640/output-2019-03-27.txt)
[output-2019-03-13.txt](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3013641/output-2019-03-13.txt)

**Comment by leepc12** [comment]
@milanmlft : Please make a tar ball of logs and post it here.

**Comment by milanmlft** [comment]
Here you go! The pipeline was killed after 2 hours (only requested this amount of walltime on HPC because previously this was more than enough for the example), so it did not get past the bowtie2 step.

Please let me know if you need anything else.

Thanks a lot for your time!

[19-03-27-test4.tar.gz](https://github.com/ENCODE-DCC/atac-seq-pipeline/files/3018794/19-03-27-test4.tar.gz)

**Comment by leepc12** [comment]
For your second run, the first task (`read_genome_data`) in a pipeline ran successfully. So I guess that something has changed on your system or you requested less resource (not enough) for the 2nd one. Please check the followings:

1) Did you run it with cromwell-34 or 38?
2) Did you run it on the same storage? (`df -h YOUR_WORK_DIR`)
3) Did you activate Conda env before running it? (`source activate encode-atac-seq-pipeline`)

**Comment by milanmlft** [comment]
Ran it with cromwell-34 after activating the conda environment.
The only thing that changed is that I tried to run it from a Scratch ($WORKDIR) file system (which should make it faster, right?) instead of my $HOME, but the pipeline itself is still exactly the same.

Will do some more test runs today.

**Comment by grrompala** [comment]
Hi again,
My issue was indeed just needing to wait longer than anticipated. 
Now, with the latest installation of the pipeline, I am seeing weird performance variability for the bowtie2 step now. I submitted 8 separate jobs for 8 paired end samples, all around 1.5 GB-- half of them got past the bowtie step around 10-12 hours and the other half are approaching 40 hours (appear to be still running fine as the bams are populating in the call-bowtie2 directory). Any guesses to what might explain this variability? As far as I can tell, the half of samples which completed quickly all ran fine through the entire pipeline (no errors).
Any insight would be appreciated-- thanks!

**Comment by leepc12** [comment]
It depends on the traffic and available resources on your cluster. Please check the actual computing hours, wall clock time and memory usage for your pipelines with `sacct -j [JOB_ID]`. Also please check your `metadata.json` file which has all resource/timing information for each task in a pipeline. You may need to look for an object named `call-bowtie2` and `shardIndex` is an 0-based replicate ID.

**Comment by CBC-KAUST** [comment]
For me this is time consuming. The whole pipeline is unusable. I gave 30 cpu and individual task per replicate. But i am confused and waiting for 80 hours for chip-seq of one TF with 3 replicates.
