### ISSUE TITLE
Questions about Running Multiple Pipelines with Cromwell Server Mode on Slurm

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/atac-seq-pipeline#94]
I am working with some people who need to run many pipelines on on Slurm cluster, and we had some clarification questions about the instructions:

1.  Does cromwell-34.jar require 2 CPUs, or is 1 CPU sufficient?

2.  Am I correct in thinking that Dconfig.file should be backends/backend.conf and not backends/backend/conf?

3.  Am I correct in thinking that individual jobs should be submitted on a login node that is different from the login node that is different from the login node in which cromwell-34.jar is running?

4.  Do individual jobs need to be submitted from login nodes on the same server, or can they be submitted from nodes on different server so long as the nodes are in the same account/partition?

5.  Once a job is submitted from a login node, does that login node need to remain open for the job to run successfully?

Thank you very much!

**Comment by leepc12** [comment]
We updated the documentation to let users use a `Local` (or `singularity`) backend instead of using cluster engine backends defined in the `backend.conf` file like `slurm` and `sge` . We recommend to run `cromwell` with a `Local` backend on HPCs. `Local` backend means that cromwell is not submitting jobs to the cluster engine.

Instead, you need to make a shell script (`$SH`) and submit it to the cluster using `sbatch $SH` or `qsub $SH`. [Example shell script](examples/local/ENCSR356KRQ_subsampled_slurm_conda.sh). This example also includes detailed instruction.

1. 1 CPU and 500MB memory are enough for `cromwell-34.jar`.
2. `-Dconfig.file=` should be `backends/backend.conf`.
3-5. Please read the above comments.

**Comment by imk1** [comment]
Thanks so much!  This is really helpful.

To make sure I understand this correctly: If I use this, then I will just be submitting a single job instead of having the pipeline submit different jobs for the different steps as I go?  Does this mean that the pipeline will be able to map reads for different replicates in parallel, call peaks for different replicates in parallel, and in other ways take advantage of the fact that I am using a cluster?

**Comment by leepc12** [comment]
Yes, replicates can still go in parallel with a local backend. It's explained in the example shell script. You can limit number of concurrent tasks in that shell script. I recommend to match it with the number of replicates.

**Comment by imk1** [comment]
Got it.  Thanks so much!  I had a few more questions:

1.  I cannot find a metadata.json file in the pipeline directory.  Should I change PIPELINE_METADATA to something else?

2.  I noticed in the test that -o workflow_opts/slurm.json was added to what I submitted.  Should I add it to the end of the script?

3.  Is there a way to specify the output directory?

**Comment by leepc12** [comment]
1. `metadata.json` is an output of cromwell. You can later use that for restarting a failed pipeline.

2. `-o FILE` must be in the shell script. Use absolute path for that JSON FILE.

3. No, there is no way to specify it. just `mkdir && cd` to that directory and run .sh there.

**Comment by imk1** [comment]
The pipeline is working for me!  Thank you so much for all of your help!
